name: CoordsCatalog
version: 1.2
main: org.minecraft.tsunami.coordsCatalog.Main
api-version: '1.17' # minimum supported version
author: Tsunami
description: A plugin to catalog coordinates.
commands:
  coordscatalog:
    description: Base command for CoordsCatalog.
    usage: /<command> help
    aliases: [cc, coords]
permissions:
  coordscatalog.save:
    description: Allows saving coordinates.
    default: op
  coordscatalog.delete:
    description: Allows deleting coordinates.
    default: op
  coordscatalog.list:
    description: Allows listing all coordinates.
    default: op
  coordscatalog.find:
    description: Allows finding coordinates by name.
    default: op
  coordscatalog.me:
    description: Allows listing own coordinates.
    default: true
  coordscatalog.check:
    description: Allows checking other players' coordinates.
    default: op
  coordscatalog.admin:
    description: Grants all CoordsCatalog permissions.
    default: op
    children:
      coordscatalog.save: true
      coordscatalog.delete: true
      coordscatalog.list: true
      coordscatalog.find: true
      coordscatalog.me: true
      coordscatalog.check: true